# Generated by Django 2.0.3 on 2018-05-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATIVIDADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITULO', models.CharField(max_length=30, verbose_name='TITULO')),
                ('DESCRICAO', models.CharField(max_length=100, verbose_name='DESCRICAO')),
                ('CONTEUDO', models.CharField(max_length=200, verbose_name='CONTEUDO')),
                ('TIPO', models.CharField(max_length=20, verbose_name='TIPO')),
                ('EXTRAS', models.CharField(max_length=200, verbose_name='EXTRAS')),
            ],
        ),
        migrations.CreateModel(
            name='PROFESSOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGIN', models.CharField(max_length=30, verbose_name='LOGIN')),
                ('SENHA', models.CharField(max_length=50, verbose_name='SENHA')),
                ('NOME', models.CharField(max_length=100, verbose_name='NOME')),
                ('EMAIL', models.EmailField(max_length=100, verbose_name='EMAIL')),
                ('CELULAR', models.CharField(max_length=50, verbose_name='CELULAR')),
                ('DT_EXPIRACAO', models.DateField(max_length=100, verbose_name='DT_EXPIRACAO')),
                ('APELIDO', models.CharField(max_length=100, verbose_name='APELIDO')),
            ],
        ),
    ]
