# Generated by Django 2.0.3 on 2018-05-02 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='ID_PROFESSOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.PROFESSOR'),
        ),
    ]
