# Generated by Django 2.0.3 on 2018-05-02 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0003_aluno_coordenador_disciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='ID_COORDENADOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.COORDENADOR'),
        ),
    ]
