# Generated by Django 2.0.3 on 2018-05-02 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banco', '0004_disciplina_id_coordenador'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATIVIDADE_VINCULADA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROTULO', models.CharField(max_length=200, verbose_name='ROTULO')),
                ('STATUS', models.CharField(max_length=20, verbose_name='STATUS')),
                ('DTINICIORESPOSTAS', models.DateField(verbose_name='DTINICIORESPOSTAS')),
                ('DTFIMRESPOSTAS', models.DateField(verbose_name='DTFIMRESPOSTAS')),
                ('ID_ATIVIDADE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.ATIVIDADE')),
            ],
        ),
        migrations.CreateModel(
            name='CURSO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NOME', models.CharField(max_length=100, verbose_name='NOME')),
            ],
        ),
        migrations.CreateModel(
            name='DISCIPLINA_OFERTADA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATA_INICIO_MATRICULA', models.DateField(verbose_name='DATA_INICIO_MATRICULA')),
                ('DATA_FIM_MATRICULA', models.DateField(verbose_name='DATA_FIM_MATRICULA')),
                ('ANO', models.IntegerField(verbose_name='ANO')),
                ('SEMESTRE', models.CharField(max_length=1, verbose_name='SEMESTRE')),
                ('TURMA', models.CharField(max_length=3, verbose_name='SEMESTRE')),
                ('METODOLOGIA', models.CharField(max_length=2000, verbose_name='METODOLOGIA')),
                ('RECURSOS', models.CharField(max_length=2000, verbose_name='RECURSOS')),
                ('CRITERIO_AVALIACAO', models.CharField(max_length=2000, verbose_name='CRITERIO_AVALIACAO')),
                ('PLANO_AULAS', models.CharField(max_length=8000, verbose_name='PLANO_AULAS')),
                ('ID_COORDENADOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.COORDENADOR')),
                ('ID_CURSO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.CURSO')),
                ('ID_DISCIPLINA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.DISCIPLINA')),
                ('ID_PROFESSOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.PROFESSOR')),
            ],
        ),
        migrations.CreateModel(
            name='ENTREGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITULO', models.CharField(max_length=40, verbose_name='TITULO')),
                ('RESPOSTA', models.CharField(max_length=100, verbose_name='RESPOSTA')),
                ('DT_ENTREGA', models.DateField(verbose_name='DT_ENTREGA')),
                ('STATUS', models.CharField(max_length=20, verbose_name='STATUS')),
                ('NOTA', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='NOTA')),
                ('DT_AVALIACAO', models.DateField(verbose_name='DT_AVALIACAO')),
                ('OBS', models.CharField(max_length=100, verbose_name='OBS')),
                ('ID_ALUNO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.ALUNO')),
                ('ID_ATIVIDADE_VINCULADA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.ATIVIDADE_VINCULADA')),
                ('ID_PROFESSOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.PROFESSOR')),
            ],
        ),
        migrations.CreateModel(
            name='MENSAGEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSUNTO', models.CharField(max_length=300, verbose_name='ASSUNTO')),
                ('REFERENCIA', models.CharField(max_length=300, verbose_name='REFERENCIA')),
                ('CONTEUDO', models.CharField(max_length=400, verbose_name='CONTEUDO')),
                ('STATUS', models.CharField(max_length=20, verbose_name='STATUS')),
                ('DT_ENVIO', models.DateField(verbose_name='DT_ENVIO')),
                ('DT_RESPOSTA', models.DateField(verbose_name='DT_RESPOSTA')),
                ('RESPOSTA', models.CharField(max_length=400, verbose_name='RESPOSTA')),
                ('ID_ALUNO', models.ManyToManyField(null=True, to='banco.ALUNO')),
                ('ID_PROFESSOR', models.ManyToManyField(null=True, to='banco.PROFESSOR')),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITACAO_MATRICULA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DTSOLICITACAO', models.DateField(verbose_name='DTSOLICITACAO')),
                ('STATUS', models.CharField(max_length=20, verbose_name='STATUS')),
                ('ID_ALUNO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.ALUNO')),
                ('ID_COORDENADOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.COORDENADOR')),
                ('ID_DISCIPLINA_OFERTADA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.DISCIPLINA_OFERTADA')),
            ],
        ),
        migrations.AddField(
            model_name='atividade_vinculada',
            name='ID_DISCIPLINA_OFERTADA',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.DISCIPLINA_OFERTADA'),
        ),
        migrations.AddField(
            model_name='atividade_vinculada',
            name='ID_PROFESSOR',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='banco.PROFESSOR'),
        ),
    ]
