# Generated by Django 2.0 on 2018-05-10 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('curriculo', '0001_initial'),
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ATIVIDADE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITULO', models.CharField(max_length=30, verbose_name='TITULO')),
                ('DESCRICAO', models.CharField(max_length=100, verbose_name='DESCRICAO')),
                ('CONTEUDO', models.CharField(max_length=200, verbose_name='CONTEUDO')),
                ('TIPO', models.CharField(max_length=20, verbose_name='TIPO')),
                ('EXTRAS', models.CharField(max_length=200, verbose_name='EXTRAS')),
                ('ID_PROFESSOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.PROFESSOR')),
            ],
        ),
        migrations.CreateModel(
            name='ATIVIDADE_VINCULADA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ROTULO', models.CharField(max_length=200, verbose_name='ROTULO')),
                ('STATUS', models.CharField(max_length=20, verbose_name='STATUS')),
                ('DTINICIORESPOSTAS', models.DateField(verbose_name='DTINICIORESPOSTAS')),
                ('DTFIMRESPOSTAS', models.DateField(verbose_name='DTFIMRESPOSTAS')),
                ('ID_ATIVIDADE', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrito.ATIVIDADE')),
                ('ID_DISCIPLINA_OFERTADA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculo.DISCIPLINA_OFERTADA')),
                ('ID_PROFESSOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.PROFESSOR')),
            ],
        ),
        migrations.CreateModel(
            name='ENTREGA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TITULO', models.CharField(max_length=40, verbose_name='TITULO')),
                ('RESPOSTA', models.CharField(max_length=100, verbose_name='RESPOSTA')),
                ('DT_ENTREGA', models.DateField(verbose_name='DT_ENTREGA')),
                ('STATUS', models.CharField(max_length=20, verbose_name='STATUS')),
                ('NOTA', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='NOTA')),
                ('DT_AVALIACAO', models.DateField(verbose_name='DT_AVALIACAO')),
                ('OBS', models.CharField(max_length=100, verbose_name='OBS')),
                ('ID_ALUNO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.ALUNO')),
                ('ID_ATIVIDADE_VINCULADA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='restrito.ATIVIDADE_VINCULADA')),
                ('ID_PROFESSOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.PROFESSOR')),
            ],
        ),
        migrations.CreateModel(
            name='SOLICITACAO_MATRICULA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DTSOLICITACAO', models.DateField(verbose_name='DTSOLICITACAO')),
                ('STATUS', models.CharField(max_length=20, verbose_name='STATUS')),
                ('ID_ALUNO', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.ALUNO')),
                ('ID_COORDENADOR', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contas.COORDENADOR')),
                ('ID_DISCIPLINA_OFERTADA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curriculo.DISCIPLINA_OFERTADA')),
            ],
        ),
    ]
