# Generated by Django 2.0 on 2018-05-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ALUNO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGIN', models.CharField(max_length=100, verbose_name='LOGIN')),
                ('SENHA', models.CharField(max_length=30, verbose_name='SENHA')),
                ('NOME', models.CharField(max_length=100, verbose_name='NOME')),
                ('EMAIL', models.EmailField(max_length=200, verbose_name='EMAIL')),
                ('CELULAR', models.IntegerField(verbose_name='CELULAR')),
                ('DT_EXPIRACAO', models.DateField(verbose_name='DT_EXPIRACAO')),
                ('RA', models.IntegerField(verbose_name='RA')),
            ],
        ),
        migrations.CreateModel(
            name='COORDENADOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGIN', models.CharField(max_length=100, verbose_name='LOGIN')),
                ('SENHA', models.CharField(max_length=30, verbose_name='SENHA')),
                ('NOME', models.CharField(max_length=30, verbose_name='NOME')),
                ('EMAIL', models.EmailField(max_length=200, verbose_name='EMAIL')),
                ('CELULAR', models.IntegerField(verbose_name='CELULAR')),
                ('DT_EXPIRACAO', models.DateField(max_length=100, verbose_name='DT_EXPIRACAO')),
            ],
        ),
        migrations.CreateModel(
            name='MENSAGEM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ASSUNTO', models.CharField(max_length=300, verbose_name='ASSUNTO')),
                ('REFERENCIA', models.CharField(max_length=300, verbose_name='REFERENCIA')),
                ('CONTEUDO', models.CharField(max_length=400, verbose_name='CONTEUDO')),
                ('STATUS', models.CharField(max_length=20, verbose_name='STATUS')),
                ('DT_ENVIO', models.DateField(verbose_name='DT_ENVIO')),
                ('DT_RESPOSTA', models.DateField(verbose_name='DT_RESPOSTA')),
                ('RESPOSTA', models.CharField(max_length=400, verbose_name='RESPOSTA')),
                ('ID_ALUNO', models.ManyToManyField(to='contas.ALUNO')),
            ],
        ),
        migrations.CreateModel(
            name='PROFESSOR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOGIN', models.CharField(max_length=30, verbose_name='LOGIN')),
                ('SENHA', models.CharField(max_length=50, verbose_name='SENHA')),
                ('NOME', models.CharField(max_length=100, verbose_name='NOME')),
                ('EMAIL', models.EmailField(max_length=100, verbose_name='EMAIL')),
                ('CELULAR', models.CharField(max_length=50, verbose_name='CELULAR')),
                ('DT_EXPIRACAO', models.DateField(max_length=100, verbose_name='DT_EXPIRACAO')),
                ('APELIDO', models.CharField(max_length=100, verbose_name='APELIDO')),
            ],
        ),
        migrations.AddField(
            model_name='mensagem',
            name='ID_PROFESSOR',
            field=models.ManyToManyField(to='contas.PROFESSOR'),
        ),
    ]
