# Generated by Django 2.0 on 2018-05-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='DT_EXPIRACAO',
            field=models.DateField(null=True, verbose_name='DT_EXPIRACAO'),
        ),
        migrations.AlterField(
            model_name='coordenador',
            name='DT_EXPIRACAO',
            field=models.DateField(max_length=100, null=True, verbose_name='DT_EXPIRACAO'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='DT_EXPIRACAO',
            field=models.DateField(max_length=100, null=True, verbose_name='DT_EXPIRACAO'),
        ),
    ]
