# Generated by Django 2.0 on 2018-05-17 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='DT_EXPIRACAO',
            field=models.DateField(null=True, verbose_name='DT_EXPIRACAO'),
        ),
    ]
