# Generated by Django 2.0 on 2018-05-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0002_auto_20180517_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='STATUS',
            field=models.CharField(max_length=7, null=True, verbose_name='STATUS'),
        ),
    ]
