# Generated by Django 2.0 on 2018-05-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculo', '0003_auto_20180517_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='ANO',
            field=models.IntegerField(null=True, verbose_name='ANO'),
        ),
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='CRITERIO_AVALIACAO',
            field=models.CharField(max_length=2000, null=True, verbose_name='CRITERIO_AVALIACAO'),
        ),
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='DATA_FIM_MATRICULA',
            field=models.DateField(null=True, verbose_name='DATA_FIM_MATRICULA'),
        ),
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='DATA_INICIO_MATRICULA',
            field=models.DateField(null=True, verbose_name='DATA_INICIO_MATRICULA'),
        ),
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='METODOLOGIA',
            field=models.CharField(max_length=2000, null=True, verbose_name='METODOLOGIA'),
        ),
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='PLANO_AULAS',
            field=models.CharField(max_length=8000, null=True, verbose_name='PLANO_AULAS'),
        ),
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='RECURSOS',
            field=models.CharField(max_length=2000, null=True, verbose_name='RECURSOS'),
        ),
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='SEMESTRE',
            field=models.CharField(max_length=1, null=True, verbose_name='SEMESTRE'),
        ),
        migrations.AlterField(
            model_name='disciplina_ofertada',
            name='TURMA',
            field=models.CharField(max_length=3, null=True, verbose_name='TURMA'),
        ),
    ]
